### ISSUE TITLE
Dead link, wrong redirection.

### ISSUE THREAD

**Issue by saahm** [os-fpga/GettingStartedWithFPGAs#2]
In [Getting Started with FPGAs](https://github.com/os-fpga/GettingStartedWithFPGAs#getting-started-with-fpgas) the link at `Visit [OSFPGA.org](https://osfpga.org/) for further learning opportunities.` currently (07/03/23) redirects to https://www.kansaschoral.com/ (some online casino scam site).

**Comment by stevehoover** [comment]
Thanks. OSFPGA was merged into CHIPS Alliance. Fixed.
